name: Deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Release API
        uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'node-typescript-docker' # Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_API_KEY}}
          usedocker: true
          appdir: 'server' # <- This will point to the api folder in your project
        env:
          HD_MONGOLAB_URI: ${{secrets.MONGOLAB_URI}}
          HD_ISSUER: ${{secrets.ISSUER}}
          HD_CLIENT_ID: ${{secrets.CLIENT_ID}}
      - name: Release Web Client
        uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'react-node-poc'
          heroku_email: ${{secrets.HEROKU_API_KEY}}
          usedocker: true
          appdir: 'client'
        env:
          HD_COME_ON: 'asdf mcgee'
